## Analísis de venta de calzados 
#### fecha: Abril 2026
#### Autor: Merlin Mirley Moreno Palacios
Fuente de los datos: https://www.kaggle.com/datasets/syedaeman2212/shoes-sales-dataset/data

##### Preguntas: 

Por medio del análisis de este dataset se intentará responder las siguientes preguntas
¿Cuál es la cantidad de unidades vendidas por mes?
 ¿Cuál es el costo promedio de ventas por marca?
¿Se encuentran precios atípicos?
 ¿Cuál es el canal por el que más se vende?

In [7]:
# importar las libreridas que se requieren para el proyecto
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv('shoes_sales_dataset.csv')
df.head(1000
        )

,Sale_ID,Date,Brand,Shoe_Type,Color,Country,Sales_Channel,Price_USD,Units_Sold,Revenue_USD
0,S1,2025-11-24,Nike,Boots,Blue,UK,Online,112.40,4,449.60
1,S2,2025-03-13,Skechers,Boots,Grey,USA,Mall,239.16,4,956.64
2,S3,2025-08-05,Nike,Running,White,UK,Mall,191.04,2,382.08
3,S4,2025-11-05,New Balance,Casual,Green,UAE,Mall,161.70,1,161.70
4,S5,2025-10-07,Adidas,Formal,Grey,France,Online,64.32,14,900.48
...,...,...,...,...,...,...,...,...,...,...
995,S996,2025-06-06,Puma,Sneakers,Red,India,Online,50.15,6,300.90
996,S997,2025-08-14,Adidas,Casual,Green,France,Online,231.81,2,463.62
997,S998,2025-02-13,Skechers,Running,White,India,Online,60.10,4,240.40
998,S999,2025-05-28,Puma,Boots,Black,France,Retail Store,239.05,1,239.05
999,S1000,2025-08-30,Puma,Casual,Green,India,Online,128.12,1,128.12

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sale_ID        1000 non-null   str
 1   Date           1000 non-null   str
 2   Brand          1000 non-null   str
 3   Shoe_Type      1000 non-null   str
 4   Color          1000 non-null   str
 5   Country        1000 non-null   str
 6   Sales_Channel  1000 non-null   str
 7   Price_USD      1000 non-null   float64
 8   Units_Sold     1000 non-null   int64
 9   Revenue_USD    1000 non-null   float64
dtypes: float64(2), int64(1), str(7)
memory usage: 78.3 KB

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], errors='coerce')
# se convierte la columna "Date" a formato de fecha, y se maneja cualquier error que pueda surgir durante la conversión.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sale_ID        1000 non-null   str
 1   Date           1000 non-null   datetime64[us]
 2   Brand          1000 non-null   str
 3   Shoe_Type      1000 non-null   str
 4   Color          1000 non-null   str
 5   Country        1000 non-null   str
 6   Sales_Channel  1000 non-null   str
 7   Price_USD      1000 non-null   float64
 8   Units_Sold     1000 non-null   int64
 9   Revenue_USD    1000 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(1), str(6)
memory usage: 78.3 KB

In [ ]:
df.describe() #

                      Date    Price_USD   Units_Sold  Revenue_USD
count                 1000  1000.000000  1000.000000   1000.00000
mean   2025-07-01 12:28:48   137.856420    10.584000   1453.18603
min    2025-01-03 00:00:00    31.020000     1.000000     32.38000
25%    2025-04-03 18:00:00    81.915000     6.000000    561.05000
50%    2025-06-28 12:00:00   139.295000    10.000000   1132.62500
75%    2025-10-03 00:00:00   193.752500    16.000000   2163.35000
max    2025-12-31 00:00:00   249.940000    20.000000   4938.40000
std                    NaN    64.270059     5.842181   1112.32648

In [ ]:
# Se obtiene el valor mínimo y máximo de cada columna, 
# para conocer el rango de fechas, precios, unidades vendidas e ingresos.

date1 = df["Date"].min()
date2 = df["Date"].max()
print(f"La fecha más antigua es: {date1}")
print(f"La fecha más reciente es: {date2}")
p1 = df["Price_USD"].min()
p2 = df["Price_USD"].max()
print(f"El precio más bajo es: {p1}")
print(f"El precio más alto es: {p2}")
u1 = df["Units_Sold"].min()
u2 = df["Units_Sold"].max()
print(f"La cantidad de unidades vendidas más baja es: {u1}")
print(f"La cantidad de unidades vendidas más alta es: {u2}")
R1 = df["Revenue_USD"].min()
R2 = df["Revenue_USD"].max()        
print(f"El ingreso más bajo es: {R1}")
print(f"El ingreso más alto es: {R2}")

La fecha más antigua es: 2025-01-03 00:00:00
La fecha más reciente es: 2025-12-31 00:00:00
El precio más bajo es: 31.02
El precio más alto es: 249.94
La cantidad de unidades vendidas más baja es: 1
La cantidad de unidades vendidas más alta es: 20
El ingreso más bajo es: 32.38
El ingreso más alto es: 4938.4